#include "test-e2k.h"

// TODO: fxcmpeqsb
// TODO: fxcmpltsb
// TODO: fxcmplesb
// TODO: fxcmpuodsb
// TODO: fxcmpneqsb
// TODO: fxcmpnltsb
// TODO: fxcmpnlesb
// TODO: fxcmpodsb
// TODO: fxcmpeqdb
// TODO: fxcmpltdb
// TODO: fxcmpledb
// TODO: fxcmpuoddb
// TODO: fxcmpneqdb
// TODO: fxcmpnltdb
// TODO: fxcmpnledb
// TODO: fxcmpoddb
// TODO: fxcmpeqxb
// TODO: fxcmpltxb
// TODO: fxcmplexb
// TODO: fxcmpuodxb
// TODO: fxcmpneqxb
// TODO: fxcmpnltxb
// TODO: fxcmpnlexb
// TODO: fxcmpodxb
// TODO: fcmpeqsb
// TODO: fcmpltsb
// TODO: fcmplesb
// TODO: fcmpuodsb
// TODO: fcmpneqsb
// TODO: fcmpnltsb
// TODO: fcmpnlesb
// TODO: fcmpodsb
// TODO: fcmpeqdb
// TODO: fcmpltdb
// TODO: fcmpledb
// TODO: fcmpuoddb
// TODO: fcmpneqdb
// TODO: fcmpnltdb
// TODO: fcmpnledb
// TODO: fcmpoddb

// TODO: fxcmpudsf
// TODO: fxcmpodsf
// TODO: fxcmpuddf
// TODO: fxcmpoddf
// TODO: fxcmpudxf
// TODO: fxcmpodxf
// TODO: fcmpeqs
// TODO: fcmplts
// TODO: fcmples
// TODO: fcmpuods
// TODO: fcmpneqs
// TODO: fcmpnlts
// TODO: fcmpnles
// TODO: fcmpods
// TODO: fcmpeqd
// TODO: fcmpltd
// TODO: fcmpled
// TODO: fcmpuodd
// TODO: fcmpneqd
// TODO: fcmpnltd
// TODO: fcmpnled
// TODO: fcmpodd
// TODO: fcmpudsf
// TODO: fcmpodsf
// TODO: fcmpuddf
// TODO: fcmpoddf

// TODO: fadds
// TODO: faddd
// TODO: fsubs
// TODO: fsubd
// TODO: fmins
// TODO: fmind
// TODO: fmaxs
// TODO: fmaxd
// TODO: fmuls
// TODO: fmuld
// TODO: fstois
// TODO: fstoistr
// TODO: istofs
// TODO: fdtoid
// TODO: fxtoid
// TODO: idtofd
// TODO: idtofx
// TODO: fxtofd
// TODO: fdtofx
// TODO: pfstois
// TODO: pfstoistr
// TODO: pistofs
// TODO: fstoid
// TODO: istofd
// TODO: istofx
// TODO: fstofd
// TODO: fstofx
// TODO: pfstofd
// TODO: fdtois
// TODO: fxtois
// TODO: fdtoistr
// TODO: idtofs
// TODO: fdtofs
// TODO: fxtofs
// TODO: pfdtois
// TODO: pfdtoistr
// TODO: pfdtofs
// TODO: fxaddss
// TODO: fxadddd
// TODO: fxaddsx
// TODO: fxadddx
// TODO: fxaddxs
// TODO: fxaddxd
// TODO: fxaddxx
// TODO: fxsubss
// TODO: fxsubdd
// TODO: fxsubsx
// TODO: fxsubdx
// TODO: fxsubxs
// TODO: fxsubxd
// TODO: fxsubxx
// TODO: fxmulss
// TODO: fxmuldd
// TODO: fxmulsx
// TODO: fxmuldx
// TODO: fxmulxs
// TODO: fxmulxd
// TODO: fxmulxx
// TODO: fxrsubss
// TODO: fxrsubdd
// TODO: fxrsubsx
// TODO: fxrsubdx

// TODO: movfi
// TODO: movif

// TODO: fxdivss
// TODO: fxdivdd
// TODO: fxdivsx
// TODO: fxdivdx
// TODO: fxdivxs
// TODO: fxdivxd
// TODO: fxdivxx
// TODO: fxsqrtisx
// TODO: fxsqrtidx
// TODO: fxsqrtixx
// TODO: fxsqrtuxx
// TODO: fxsqrtusx
// TODO: fxsqrtudx
// TODO: fxsqrttxx
// TODO: fxsqrttsx
// TODO: fxsqrttdx
// TODO: fxdivtss
// TODO: fxdivtdd
// TODO: fxdivtsx
// TODO: fxdivtdx

// TODO: pfadds
// TODO: pfaddd
// TODO: pfsubs
// TODO: pfsubd
// TODO: pfmins
// TODO: pfmind
// TODO: pfmaxs
// TODO: pfmaxd
// TODO: pfmuls
// TODO: pfmuld
// TODO: pfcmpeqs
// TODO: pfcmplts
// TODO: pfcmples
// TODO: pfcmpuods
// TODO: pfcmpneqs
// TODO: pfcmpnlts
// TODO: pfcmpnles
// TODO: pfcmpods
// TODO: pfcmpeqd
// TODO: pfcmpltd
// TODO: pfcmpled
// TODO: pfcmpuodd
// TODO: pfcmpneqd
// TODO: pfcmpnltd
// TODO: pfcmpnled
// TODO: pfcmpodd

// TODO: fdivs
// TODO: fdivd
// TODO: pfdivs
// TODO: pfdivd
// TODO: fsqrts
// TODO: fsqrtid
// TODO: pfsqrts
// TODO: frcps
// TODO: fsqrttd
// TODO: pfsqrttd
// TODO: frsqrts

int main(int argc, char *argv[]) {
    return is_failed();
}
