# -*- Mode: makefile -*-
#
# E2K tests
#

E2K_SRC_PATH = $(SRC_PATH)/tests/tcg/e2k
E2K_SRC_PATH_ASM = $(E2K_SRC_PATH)/asm

# Set search path for all sources
VPATH += $(E2K_SRC_PATH)
VPATH += $(E2K_SRC_PATH_ASM)

E2K_SRCS_ASM = $(notdir $(wildcard $(E2K_SRC_PATH_ASM)/*.S))
E2K_TESTS_ASM = $(E2K_SRCS_ASM:.S=)

$(E2K_TESTS_ASM): LDFLAGS += -nostdlib

E2K_SRCS = $(notdir $(wildcard $(E2K_SRC_PATH)/*.c))
E2K_TESTS = $(E2K_SRCS:.c=)

# set light optimization level to reduce binary size
e2k-v1: CFLAGS += -O1

E2K_ALL_TESTS := $(E2K_TESTS_ASM) $(E2K_TESTS)
TESTS = $(MULTIARCH_TESTS) $(E2K_ALL_TESTS)

%.o: %.s
	$(CC) -c $(CFLAGS) -o $@ $<

%: %.o
	$(LD) $(LDFLAGS) -o $@ $<
