# Default configuration for e2k-softmmu

# Dev:
#
CONFIG_APIC=y
CONFIG_IOAPIC=y
CONFIG_PCI=y
CONFIG_ELBRUS_SIM_CONSOLE=y
CONFIG_PCI_IOHUB=y
CONFIG_VGA_CIRRUS=y
CONFIG_VGA_PCI=y
CONFIG_ATI_VGA=y
CONFIG_ESCC_PCI=y
